### ISSUE TITLE
Add Last REV PCB

### ISSUE THREAD

**Issue by Mlebailly22** [proficnc/The-Cube#190]
Hi, 
Your project is really awesome, but is it possible to add the Altium Project of the last REV of the Carrier Board, I have the REV E in my hand, I don't know if it's the last one, but that could be incredible to see the schematics.

Maybe the project is already somewhere on Internet, but I can't find it thanks for your help.

**Comment by proficnc** [comment]
The reason for this is that it has parts that don't share the same license, sorry about that!

**Comment by Mlebailly22** [comment]
Oh Okay, Is that because of the Ping (PF800) part ?

**Comment by proficnc** [comment]
yes
