### ISSUE TITLE
Specs for the MOSFET-DUAL-PCHANNEL-CHIPFET on PSM_components.SchDoc

### ISSUE THREAD

**Issue by NicolasMontoyaS** [proficnc/The-Cube#34]
Hello, 
It would be nice to mention the part number / have a more descriptive name for the MOSFET-DUAL-PCHANNEL-CHIPFET's used in the PSM_components.SchDoc. Like the current/voltage specs.

Thanks!

**Comment by proficnc** [comment]
https://www.onsemi.com/pub/Collateral/NTHD4102P-D.PDF
