### ISSUE TITLE
The RN801B1M does not link to an actual component in PSM_components.SchDoc

### ISSUE THREAD

**Issue by NicolasMontoyaS** [proficnc/The-Cube#36]
The RN801A/B/C/D1M component using in the PSM_components.SchDoc does not refer to an actual component when googled. I believe it is a resistor, but another symbol is used for the resistor throughout the schematic, so the component is ambiguous.

**Comment by proficnc** [comment]
What are you trying to do with it? 
The PSM is my design and licensing is -NC all I have released is the schematics as is how is. 
This is as a reference for people who want to know the functionality of the design so they can integrate the module in their carrier board design. 
If you would like detailed assistance with the design, feel free to ask on our forums at CubePilot.org

**Comment by proficnc** [comment]
It’s a 1M pull-up resistor btw. In a network. 

I would prefer you ask support questions on the forums, these issues are for faults etc, highlighting mistakes, not for support. 

Discuss.cubepilot.org

**Comment by NicolasMontoyaS** [comment]
Oh ok, thank you, I was not aware. I just wanted to embed the PSM into my custom carrier board so I do not have to worry about buying the module separately (and in case they ever go out-of-stock). I will ask more questions on the forums, thank you.

**Comment by proficnc** [comment]
We guarantee it’s availability, It is used on about 40 different carrier boards now for OEM companies. Please contact Your local reseller, and let them know that I have sent you to them, they can get the PSM module.

By using the module, you are guaranteed that it is a tested proven system. Very small changes to the design can lead to totally unexpected behaviour changes.  We have proven this design over 5 years now, and perfected our manufacturing of it.
